### ISSUE TITLE
Is a NuGet package planned?

### ISSUE THREAD

**Issue by thoemmi** [LordMike/DeviceIOControlLib#2]
This is a great library :+1: 

Currently I'm copying parts as I need to my project. However, I'd rather add a reference to a NuGet package. Do you plan to publish `DeviceIOControlLib` as such a package?

**Comment by LordMike** [comment]
Hi,

I originally thought this was a good idea, but then I came around. I don't think I will publish a Nuget package for this project. Not now, probably never.

There are a few reasons, some of them I will list:

* Maintenance - yet another project to keep updated
* It's incomplete - there are thousands of control codes, very few are implemented here. So this library might be used a little bit, but then you end up copying code anyways.
* To cover all above cases would make it huge and bloated

We might get around some of it if the project received a loving rewrite, where the core functionality - invoking the Win32 method - was split out, and then any concrete use case could be put on top. E.g. `DeviceIoControl` and `DeviceIoControl.Volumes`-style projects.

But I won't do that now. Thanks for dropping a note though :) - happy you could use it.

**Comment by thoemmi** [comment]
I do understand your points. Compilation and publishing on NuGet could be automated, but maybe it's not worth the effort. 
So DeviceIOControlLib is not a library you just drop in but a repository of source code which you can copy to your own project. I'm fine with that, as I only need a small portion of it. :wink:

**Comment by thoemmi** [comment]
I guess you've changed your mind: https://www.nuget.org/packages/DeviceIOControlLib/

**Comment by LordMike** [comment]
I had completely forgotten about this issue.

I had a stint where I repackaged all my projects to project.json / dotnet core, and in so I put them all through appveyor and on to Nuget. This project cam in that batch.

The issue reg. completeness still stands, but I've resolved to building it as needed as covering "all" codes (if we can even define all) is impossible.
